const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT, 10) || 587,
  secure: true,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

/**
 * Send the generated sales report to the specified email.
 * @param {string} to        — Recipient email address
 * @param {string} htmlBody  — HTML content of the report
 * @param {string} fileName  — Original file name (used in subject)
 * @returns {Promise<Object>} — Nodemailer send result
 */
async function sendReport(to, htmlBody, fileName) {
  const mailOptions = {
    from: `"RabbitAI Reports" <${process.env.SMTP_FROM || process.env.SMTP_USER}>`,
    to,
    subject: `📊 Sales Report — ${fileName}`,
    html: `
      <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 720px; margin: 0 auto; color: #1a1a2e;">
        <div style="background: linear-gradient(135deg, #6366f1, #8b5cf6); padding: 24px 32px; border-radius: 12px 12px 0 0;">
          <h1 style="color: #fff; margin: 0; font-size: 22px;">🐇 RabbitAI Sales Report</h1>
          <p style="color: #e0e0ff; margin: 4px 0 0; font-size: 14px;">Auto-generated analysis for <strong>${fileName}</strong></p>
        </div>
        <div style="padding: 24px 32px; background: #ffffff; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 12px 12px;">
          ${htmlBody}
          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;" />
          <p style="font-size: 12px; color: #9ca3af;">This report was generated by RabbitAI using AI-powered analysis. Made by ${process.env.SMTP_USER}.</p>
        </div>
      </div>
    `,
  };

  const result = await transporter.sendMail(mailOptions);
  console.log(`[EMAIL] Sent to ${to} — messageId: ${result.messageId}`);
  return result;
}

module.exports = { sendReport };
